version: '3'

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "customers"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user4040"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pgdata:
